apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017

        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
          
      volumes:
        - name: mongo-data
          emptyDir: {}