apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: act03-contenedores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017

        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
          
      volumes:
      - name: mongo-data
        hostPath:
          path: /mnt/data/mongo
          type: DirectoryOrCreate