apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
  namespace: act03-contenedores
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000