name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'nodeapp/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Tag Version
      id: tag_version
      run: |
        last_tag=$(git tag --sort=-v:refname | head -n 1)
        if [ -z "$last_tag" ]; then
          new_tag="v1.0"
        else
          version=$(echo $last_tag | sed 's/v//')
          major=$(echo $version | cut -d. -f1)
          minor=$(echo $version | cut -d. -f2)
          new_tag="v${major}.$((minor+1))"
        fi
        echo "new_tag=$new_tag" >> $GITHUB_ENV
        echo "::set-output name=new_tag::$new_tag"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./nodeapp
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/aleksunir:${{ env.new_tag }}
          ${{ secrets.DOCKER_USERNAME }}/aleksunir:latest

    - name: Create GitHub Tag
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "${{ env.new_tag }}"
        tag_exists_error: false
        message: "Release ${{ env.new_tag }}"


